version: '3.7'
services:
  api:
    image: golang:latest
    command: sh -c "/go-scripts/goStart.sh"
    environment:
      - GOROOT=/usr/local/go
      - GOPATH=/go
      - DBNAME=${DB_NAME}
      - DBURL=mongodb://${DB_USER}:${DB_PASS}@${DB_HOST}
      - SERVE=${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
        - "./packages/go-api/src:/go/src"
        - "./scripts:/go-scripts"
    working_dir: "/go-scripts"
  db-seed:
    command: sh -c "/scripts/wait-for.sh db:${DB_PORT} -- /scripts/generateSeed.sh"
    depends_on:
      - db
    image: node:latest
    working_dir: "/generator"
    volumes:
      - "./scripts:/scripts"
      - "./libs/generator:/generator"
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASS}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - "./scripts:/mongo"
